import { StyleSheet } from 'react-native';

export const finishStyles = StyleSheet.create({
  root: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#fff', 
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 30,
    paddingVertical: 20,
  },
  playerColumn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardShadow: {
    backgroundColor: '#f6f8fa',
    borderRadius: 18,
    padding: 22,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.12,
    shadowRadius: 7,
    elevation: 5,
    minWidth: 140,
  },
  avatar: {
    width: 90,
    height: 90,
    borderRadius: 45,
    borderWidth: 2,
    borderColor: '#4fd1c5',
    marginBottom: 10,
    backgroundColor: '#fff',
  },
  playerName: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2a2a2a',
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  score: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#4fd1c5',
    marginTop: 2,
    textShadowColor: '#eee',
    textShadowOffset: { width: 1, height: 2 },
    textShadowRadius: 1,
  },
  centerColumn: {
    flex: 2,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#222',
    marginBottom: 16,
    letterSpacing: 1.1,
  },
  scoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    marginTop: 2,
  },
  bigScore: {
    fontSize: 48,
    fontWeight: 'bold',
    color: '#4fd1c5',
    marginHorizontal: 15,
    textShadowColor: '#eee',
    textShadowOffset: { width: 1, height: 2 },
    textShadowRadius: 2,
  },
  colon: {
    fontSize: 48,
    fontWeight: 'bold',
    color: '#888',
    marginHorizontal: 6,
  },
  timeUsed: {
    fontSize: 28, 
    color: '#555',
    marginBottom: 18,
    marginTop: 6,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  winnerBox: {
    alignItems: 'center',
    marginBottom: 18,
    marginTop: 6,
    backgroundColor: '#f6f8fa',
    borderRadius: 14,
    padding: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.10,
    shadowRadius: 4,
    elevation: 3,
    minWidth: 150,
    maxWidth: 240,
  },
  winnerLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#ffd700',
    marginBottom: 2,
    letterSpacing: 0.7,
  },
  winnerAvatar: {
    width: 70,
    height: 70,
    borderRadius: 35,
    borderWidth: 3,
    borderColor: '#ffd700',
    marginVertical: 4,
    backgroundColor: '#fff',
  },
  winnerName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#ffd700',
    letterSpacing: 1,
    marginTop: 2,
    textShadowColor: '#eee',
    textShadowOffset: { width: 1, height: 2 },
    textShadowRadius: 1,
  },
  leaderboardBtn: {
    marginTop: 18,
    backgroundColor: '#4fd1c5',
    paddingVertical: 14,
    paddingHorizontal: 38,
    borderRadius: 12,
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.13,
    shadowRadius: 4,
    elevation: 4,
  },
  leaderboardBtnText: {
    color: '#222',
    fontSize: 20,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
});
