import { StyleSheet } from 'react-native';

export const leaderboardStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    paddingTop: 50,
  },
  header: {
    alignItems: 'center',
    marginBottom: 25,
    paddingHorizontal: 20,
  },
  title: {
    fontSize: 32,
    fontWeight: '900',
    color: '#ffffff',
    textAlign: 'center',
    letterSpacing: 1.5,
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: 'rgba(255,255,255,0.8)',
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  searchContainer: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 15,
    fontSize: 16,
    color: '#ffffff',
    fontWeight: '600',
  },
  listContainer: {
    paddingHorizontal: 15,
    paddingBottom: 30,
  },
  itemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 20,
    paddingVertical: 15,
    paddingHorizontal: 15,
    marginVertical: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  separator: {
    height: 8,
  },
  rankSection: {
    alignItems: 'center',
    marginRight: 15,
    minWidth: 45,
  },
  rankNumber: {
    fontSize: 18,
    fontWeight: '800',
    color: '#666',
    textAlign: 'center',
  },
  topThreeRank: {
    fontSize: 22,
    color: '#FFD700',
    textShadowColor: 'rgba(255, 215, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  rankEmoji: {
    fontSize: 16,
    marginTop: 2,
  },
  avatarSection: {
    position: 'relative',
    marginRight: 15,
  },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#667eea',
    backgroundColor: '#fff',
  },
  topThreeAvatar: {
    width: 55,
    height: 55,
    borderRadius: 27.5,
    borderWidth: 3,
    borderColor: '#FFD700',
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 4,
  },
  avatarPlaceholder: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#e0e0e0',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#667eea',
  },
  avatarIcon: {
    fontSize: 20,
    color: '#999',
  },
  crownIcon: {
    position: 'absolute',
    top: -8,
    right: -8,
    fontSize: 20,
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: 12,
    width: 24,
    height: 24,
    textAlign: 'center',
    lineHeight: 24,
  },
  playerInfo: {
    flex: 1,
    marginRight: 15,
  },
  name: {
    fontSize: 17,
    fontWeight: '700',
    color: '#333',
    marginBottom: 2,
    letterSpacing: 0.3,
  },
  topThreeName: {
    fontSize: 18,
    color: '#FFD700',
    textShadowColor: 'rgba(255, 215, 0, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  tapHint: {
    fontSize: 12,
    color: '#888',
    fontStyle: 'italic',
  },
  scoreSection: {
    alignItems: 'flex-end',
    minWidth: 70,
  },
  points: {
    fontSize: 16,
    fontWeight: '800',
    color: '#4CAF50',
    marginBottom: 4,
  },
  topThreePoints: {
    fontSize: 18,
    color: '#FFD700',
    textShadowColor: 'rgba(255, 215, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  progressBar: {
    width: 60,
    height: 6,
    backgroundColor: '#e0e0e0',
    borderRadius: 3,
    overflow: 'hidden',
  },
  topThreeProgress: {
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 2,
  },
  progressFill: {
    height: '100%',
    borderRadius: 3,
  },
  firstPlace: {
    backgroundColor: 'rgba(255, 215, 0, 0.15)',
    borderColor: 'rgba(255, 215, 0, 0.5)',
    borderWidth: 2,
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  secondPlace: {
    backgroundColor: 'rgba(192, 192, 192, 0.15)',
    borderColor: 'rgba(192, 192, 192, 0.5)',
    borderWidth: 2,
    shadowColor: '#C0C0C0',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  thirdPlace: {
    backgroundColor: 'rgba(205, 127, 50, 0.15)',
    borderColor: 'rgba(205, 127, 50, 0.5)',
    borderWidth: 2,
    shadowColor: '#CD7F32',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
});

export const leaderboardModalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: {
    width: '90%',
    maxHeight: '80%',
    backgroundColor: '#ffffff',
    borderRadius: 25,
    padding: 25,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 15,
  },
  closeBtn: {
    position: 'absolute',
    right: 20,
    top: 15,
    zIndex: 10,
    padding: 5,
  },
  closeText: {
    fontSize: 24,
    color: '#999',
    fontWeight: 'bold',
  },
  profileCircle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#f0f0f0',
    marginBottom: 15,
    marginTop: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    marginBottom: 15,
    marginTop: 20,
    backgroundColor: '#f0f0f0',
    borderWidth: 3,
    borderColor: '#667eea',
  },
  playerName: {
    fontSize: 24,
    fontWeight: '800',
    marginBottom: 5,
    color: '#333',
    textAlign: 'center',
  },
  tabRow: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'center',
    marginBottom: 20,
    marginTop: 15,
    borderBottomWidth: 1,
    borderColor: '#f0f0f0',
  },
  tabActive: {
    fontWeight: '700',
    fontSize: 16,
    color: '#667eea',
    marginHorizontal: 20,
    paddingBottom: 10,
    borderBottomWidth: 3,
    borderColor: '#667eea',
  },
  tabInactive: {
    fontSize: 16,
    color: '#999',
    marginHorizontal: 20,
    paddingBottom: 10,
  },
  matchesList: {
    width: '100%',
    marginTop: 10,
  },
  noMatchesText: {
    color: '#999',
    textAlign: 'center',
    fontSize: 16,
    fontStyle: 'italic',
    marginTop: 20,
  },
  matchRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 5,
    borderBottomWidth: 1,
    borderBottomColor: '#f5f5f5',
  },
  matchOpponent: {
    flex: 1,
    fontSize: 14,
    color: '#333',
    fontWeight: '600',
  },
  matchResult: {
    width: 70,
    textAlign: 'center',
    fontWeight: '600',
    fontSize: 14,
  },
  matchDate: {
    width: 80,
    textAlign: 'center',
    color: '#666',
    fontSize: 12,
  },
  winLoseBox: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  winLoseText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 12,
    letterSpacing: 1,
  },
  win: {
    backgroundColor: '#4CAF50',
  },
  lose: {
    backgroundColor: '#f44336',
  },
});
