import { Dimensions, StyleSheet } from 'react-native';

const { width, height } = Dimensions.get('window');

export const playerStyles = StyleSheet.create({
  container: {
    paddingTop: 50,
    paddingHorizontal: 20,
    paddingBottom: 40,
    backgroundColor: '#0B4D2C',
    minHeight: height,
  },
  headerSection: {
    alignItems: 'center',
    marginBottom: 40,
  },
  headerRow: {
    width: '100%',
    alignItems: 'flex-end',
    marginBottom: 20,
  },
  historyButton: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  historyButtonText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 16,
    letterSpacing: 0.5,
  },
  header: {
    fontSize: 32,
    fontWeight: '900',
    color: '#ffffff',
    textAlign: 'center',
    letterSpacing: 1.2,
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 16,
    color: 'rgba(255,255,255,0.8)',
    textAlign: 'center',
    letterSpacing: 0.5,
    fontStyle: 'italic',
  },
  section: {
    marginBottom: 35,
    width: '100%',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  title: {
    fontSize: 24,
    fontWeight: '800',
    color: '#ffffff',
    letterSpacing: 0.8,
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  selectedIndicator: {
    fontSize: 14,
    color: '#FFD700',
    fontWeight: '600',
    backgroundColor: 'rgba(255, 215, 0, 0.2)',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'rgba(255, 215, 0, 0.5)',
  },
  scrollContainer: {
    flexDirection: 'row',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  playerContainer: {
    alignItems: 'center',
    marginHorizontal: 8,
  },
  playerTouchable: {
    alignItems: 'center',
  },
  ballAndFlagContainer: {
    position: 'relative',
    width: 130,
    height: 130,
    marginBottom: 8,
  },
  billiardBall: {
    width: 130,
    height: 130,
    borderRadius: 65,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 10,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.3)',
    position: 'relative',
    overflow: 'hidden',
  },
  ballGloss: {
    position: 'absolute',
    top: 8,
    left: 15,
    width: 45,
    height: 25,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    borderRadius: 20,
    transform: [{ rotate: '-30deg' }],
  },
  avatarContainer: {
    width: 65,
    height: 65,
    borderRadius: 32.5,
    backgroundColor: '#87CEEB',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#4169E1',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  avatar: {
    width: 55,
    height: 55,
    borderRadius: 27.5,
  },
  nationalityOverlay: {
    position: 'absolute',
    bottom: -10, 
    right: -10,  
    width: 45,   
    height: 45,
    borderRadius: 22.5,
    backgroundColor: '#DC143C', 
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
    elevation: 15, 
    zIndex: 10,    
  },
  nationality: {
    width: 35,
    height: 35,
    borderRadius: 17.5,
  },
  playerName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#fff',
    textAlign: 'center',
    letterSpacing: 0.5,
    textShadowColor: 'rgba(0,0,0,0.8)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
    marginTop: 4,
    maxWidth: 120,
  },
  selectedBall: {
    borderWidth: 4,
    borderColor: '#FFD700',
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.6,
    shadowRadius: 15,
    elevation: 15,
    transform: [{ scale: 1.05 }],
  },
  selectedGlow: {
    position: 'absolute',
    top: -8,
    left: -8,
    backgroundColor: '#FFD700',
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.6,
    shadowRadius: 8,
    elevation: 8,
  },
  selectedCheckmark: {
    color: '#333',
    fontSize: 16,
    fontWeight: '900',
  },
  stripesContainer: {
    position: 'absolute',
    top: -45,     
    left: 0,
    right: 0,
    bottom: -45,
    borderRadius: 65,
    overflow: 'hidden',
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignItems: 'stretch',
  },
  stripe: {
    flex: 1,
    opacity: 0.9,
  },
  
  billiardTable: {
    backgroundColor: '#0B4D2C', 
    borderRadius: 20,
    padding: 25,
    marginVertical: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 12,
    borderWidth: 8,
    borderColor: '#6B4423', 
    position: 'relative',
  },
  tableHeader: {
    alignItems: 'center',
    marginBottom: 25,
  },
  tableTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: '#FFD700', 
    letterSpacing: 2,
    textShadowColor: 'rgba(0,0,0,0.7)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  tableSubtitle: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.8)',
    fontStyle: 'italic',
    marginTop: 5,
  },
  tableRail: {
    backgroundColor: 'rgba(107, 68, 35, 0.8)', 
    borderRadius: 15,
    marginVertical: 10,
    padding: 15,
    borderWidth: 2,
    borderColor: '#8B4513',
  },
  railSection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  ballIndicator: {
    width: 35,
    height: 35,
    borderRadius: 17.5,
    backgroundColor: '#FFD700',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFA500',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 5,
    elevation: 5,
  },
  ballNumber: {
    fontSize: 16,
    color: '#333',
  },
  railLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFD700',
    flex: 1,
    textAlign: 'center',
    letterSpacing: 1,
  },
  cueStick: {
    backgroundColor: '#D2B48C', 
    borderRadius: 25,
    minWidth: 150, 
    height: 55,     
    borderWidth: 2,
    borderColor: '#8B4513',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
    justifyContent: 'center', 
  },
  picker: {
    height: 51,       
    color: '#2F1B14',
    fontWeight: '600',
    fontSize: 16,     
    textAlign: 'center',
  },
  
matchupTable: {
  backgroundColor: '#0B4D2C',
  borderRadius: 25,
  padding: 25,
  marginVertical: 20,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 12 },
  shadowOpacity: 0.4,
  shadowRadius: 25,
  elevation: 18,
  borderWidth: 6,
  borderColor: '#6B4423',
  position: 'relative',
},

matchupHeader: {
  alignItems: 'center',
  marginBottom: 20,
},

matchupTitle: {
  fontSize: 26,
  fontWeight: '900',
  color: '#FFD700',
  letterSpacing: 2,
  textShadowColor: 'rgba(0,0,0,0.8)',
  textShadowOffset: { width: 0, height: 2 },
  textShadowRadius: 4,
},

matchupSubtitle: {
  fontSize: 14,
  color: 'rgba(255,255,255,0.8)',
  fontStyle: 'italic',
  marginTop: 5,
},

battleArena: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-around',
  marginVertical: 20,
  paddingVertical: 15,
  backgroundColor: 'rgba(255,255,255,0.1)',
  borderRadius: 15,
},

playerBallContainer: {
  alignItems: 'center',
  flex: 1,
},

matchBall: {
  width: 80,
  height: 80,
  borderRadius: 40,
  alignItems: 'center',
  justifyContent: 'center',
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 6 },
  shadowOpacity: 0.4,
  shadowRadius: 10,
  elevation: 10,
  borderWidth: 2,
  borderColor: 'rgba(255,255,255,0.3)',
  position: 'relative',
  overflow: 'hidden',
  marginBottom: 10,
},

battlePlayerName: {
  fontSize: 16,
  fontWeight: '700',
  color: '#FFD700',
  textAlign: 'center',
  textShadowColor: 'rgba(0,0,0,0.8)',
  textShadowOffset: { width: 0, height: 1 },
  textShadowRadius: 2,
},

vsIndicator: {
  alignItems: 'center',
  marginHorizontal: 15,
},

vsText: {
  fontSize: 20,
  fontWeight: '900',
  color: '#FFD700',
  letterSpacing: 2,
  textShadowColor: 'rgba(0,0,0,0.8)',
  textShadowOffset: { width: 0, height: 2 },
  textShadowRadius: 3,
},

vsLine: {
  width: 40,
  height: 3,
  backgroundColor: '#FFD700',
  marginTop: 5,
  borderRadius: 2,
},

matchInfo: {
  alignItems: 'center',
  marginVertical: 15,
  paddingVertical: 10,
  backgroundColor: 'rgba(107, 68, 35, 0.6)',
  borderRadius: 12,
},

matchInfoText: {
  fontSize: 16,
  color: '#FFD700',
  fontWeight: '600',
  textAlign: 'center',
  letterSpacing: 1,
},

breakButton: {
  alignSelf: 'center',
  marginTop: 10,
},

cueStickButton: {
  backgroundColor: '#8B4513',
  paddingVertical: 18,
  paddingHorizontal: 40,
  borderRadius: 30,
  borderWidth: 3,
  borderColor: '#D2B48C',
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 8 },
  shadowOpacity: 0.4,
  shadowRadius: 15,
  elevation: 10,
  minWidth: width * 0.7,
  alignItems: 'center',
},

breakButtonText: {
  color: '#FFD700',
  fontSize: 20,
  fontWeight: '900',
  letterSpacing: 2,
  textShadowColor: 'rgba(0,0,0,0.8)',
  textShadowOffset: { width: 0, height: 1 },
  textShadowRadius: 2,
},

});
