import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

export const gameStyles = StyleSheet.create({
  background: {
    flex: 1,
    resizeMode: 'cover',
    padding: 20,
  },
  landscapeRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 30,
  },
  sidePlayer: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  playerContainer: {
    position: 'relative',
    alignItems: 'center',
    marginBottom: 12,
  },
  avatarLarge: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 4,
    borderColor: '#FFD700',
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 10,
  },
  playerBadge: {
    position: 'absolute',
    top: -8,
    right: -8,
    backgroundColor: '#FF6B6B',
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#fff',
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  playerBadgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  playerName: {
    fontSize: 18,
    fontWeight: '800',
    color: '#fff',
    textAlign: 'center',
    textShadowColor: 'rgba(0,0,0,0.7)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    letterSpacing: 0.5,
  },
  centerBlock: {
    flex: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scoreSnapRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 30,
    marginTop: 20,
  },
  scoreSnapColumn: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  scoreSnapMiddle: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 140,
    marginHorizontal: 20,
  },
  vsLarge: {
    fontSize: 40,
    marginBottom: 15,
    textAlign: 'center', 
  },
  timerContainer: {
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 20,
    paddingVertical: 15,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center', 
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 3,
    borderColor: '#4CAF50',
    minWidth: 140, 
    width: 140,    
    height: 80,    
  },
  timerLarge: {
    fontSize: 28,
    fontWeight: '900',
    color: '#4CAF50',
    letterSpacing: 1,
    textAlign: 'center',
    minWidth: 100, 
    includeFontPadding: false, 
    textAlignVertical: 'center', 
  },
  timerLabel: {
    fontSize: 12,
    color: '#666',
    fontWeight: '700',
    marginTop: 4,
    letterSpacing: 2,
    textAlign: 'center',
  },
  playerLabel: {
    fontSize: 16,
    color: '#fff',
    marginTop: 12,
    fontWeight: '700',
    letterSpacing: 1,
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  finishButton: {
    backgroundColor: '#FFD700',
    paddingVertical: 18,
    paddingHorizontal: 40,
    borderRadius: 25,
    marginTop: 25,
    alignSelf: 'center',
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 15,
    elevation: 10,
    borderWidth: 2,
    borderColor: '#FFA500',
  },
  finishButtonText: {
    color: '#333',
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: 1,
    textShadowColor: 'rgba(255,255,255,0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  modalContent: {
    width: '85%',
    backgroundColor: '#fff',
    borderRadius: 25,
    padding: 30,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 15,
  },
  modalHeader: {
    fontSize: 26,
    fontWeight: '900',
    marginBottom: 20,
    color: '#333',
    letterSpacing: 1,
  },
  modalPlayersRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#4CAF50',
  },
  modalVs: {
    fontSize: 20,
    fontWeight: '900',
    color: '#666',
    marginHorizontal: 20,
    letterSpacing: 1,
  },
  modalText: {
    fontSize: 18,
    marginVertical: 6,
    color: '#333',
    fontWeight: '600',
  },
  modalScore: {
    fontSize: 32,
    fontWeight: '900',
    color: '#4CAF50',
    marginVertical: 12,
    letterSpacing: 2,
  },
  confirmButton: {
    marginTop: 25,
    backgroundColor: '#4CAF50',
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 15,
    shadowColor: '#4CAF50',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  confirmButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  cancelText: {
    marginTop: 15,
    color: '#999',
    fontSize: 16,
    fontWeight: '600',
  },
});
